import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'hi' | 'pa';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    tagline: "Rural Healthcare Made Simple",
    welcome: "Welcome to Healthcare",
    welcomeDesc: "Connect with doctors, manage health records, and get medical help - all from your village",
    patient: "Patient",
    doctor: "Doctor", 
    patientDesc: "Get medical consultation and manage your health records",
    doctorDesc: "Manage patients and provide teleconsultations",
    consultation: "Video Call",
    records: "Health Card",
    symptomCheck: "AI Check",
    emergency: "Emergency",
    patients: "My Patients",
    analytics: "Reports",
    prescriptions: "Medicine",
    appointments: "Schedule",
    poweredBy: "Government of State Health Initiative",
    online: "Online",
    offline: "Offline",
    
    myHealthCard: "My Health Card",
    talkToDoctor: "Talk to Doctor",
    checkSymptoms: "Check Symptoms",
    emergencyHelp: "Emergency Help",

    voiceHelp: "Voice Help",
    settings: "Settings",
    
    callAmbulance: "Call Ambulance",
    nearestHospital: "Nearest Hospital",
    policHelp: "Police Help",
    emergencyContacts: "Emergency Contacts",
    
    listening: "Listening...",
    tapToSpeak: "Tap to Speak",
    
    microphonePermissionTitle: "Enable Voice Features",
    microphonePermissionDesc: "Kutumbh Care uses voice commands to help you navigate and describe symptoms. This makes the app easier to use, especially for emergency situations.",
    allowMicrophone: "Allow Microphone Access",
    continueWithoutVoice: "Continue Without Voice",
    microphoneSecurityNote: "Your voice data stays private and is processed locally on your device.",
    microphoneAccessGranted: "Microphone access granted! Voice features are now available.",
    microphoneAccessDenied: "Microphone access denied. Voice features will not work.",
    noMicrophoneFound: "No microphone found. Please connect a microphone.",
    microphoneNotSupported: "Microphone not supported on this device.",
    microphoneError: "Error accessing microphone",
    httpsRequired: "Voice features require HTTPS connection",
    voiceFeaturesLimited: "Voice features will be limited without microphone access.",
    voiceEnabled: "Voice",
    voiceDisabled: "No Voice",
    voiceUnknown: "Voice?",
    howToEnableVoice: "How to enable voice features:",
    clickMicrophoneIcon: "Click the microphone icon in your browser address bar",
    selectAllow: "Select 'Allow' for microphone access",
    refreshIfNeeded: "Refresh the page if needed",
    lookForMicIcon: "Look for 🎤 or 🔒 icon next to the website address",
    
    patientId: "Patient ID",
    age: "Age",
    bloodGroup: "Blood Group",
    allergies: "Allergies",
    medications: "Current Medications",
    lastVisit: "Last Visit",
    
    findDoctor: "Find Doctor",
    availableDoctors: "Available Doctors",
    startCall: "Start Call",
    
    describeSymptoms: "Describe your symptoms",
    commonSymptoms: "Common Symptoms",
    fever: "Fever",
    cough: "Cough",
    headache: "Headache",
    stomachPain: "Stomach Pain",
    
    todayAppointments: "Today's Appointments",
    patientRecords: "Patient Records",
    prescriptionPad: "Prescription Pad",
    healthAnalytics: "Health Analytics",
    
    findHospitals: "Find Hospitals",
    loading: "Loading",
    signOutSuccessful: "Signed out successfully",
    demoAccountDesc: "Experience all features instantly without setup",
    loginWelcomeDesc: "Access healthcare services designed for rural communities with voice support in Statei, Hindi, and English.",
    
    chooseLoginMethod: "Choose Login Method",
    demoLogin: "Demo Login",
    instantAccess: "Instant access, no setup",
    signInWithAccount: "Sign In With Account",
    forRegisteredUsers: "For registered users",
    backToLogin: "Back to Login",
    chooseDemoProfile: "Choose Demo Profile",
    demoPatient: "Demo Patient",
    demoDoctor: "Demo Doctor",
    familyHealthcareManagement: "Family healthcare management",
    healthcareProviderDashboard: "Healthcare provider dashboard",
    family: "Family",
    patientPortal: "Patient Portal",
    noRegistrationRequired: "No registration required",
    fullFeatureAccess: "Full feature access",
    worksOffline: "Works offline",
    
    selectFamilyMember: "Select Family Member",
    chooseFamilyMemberDesc: "Choose which family member needs healthcare services today.",
    personalizedHealthcareFeatures: "Each member has personalized healthcare features and records",
    me: "Me",
    wife: "Wife",
    child: "Child",
    myHealthRecords: "My Health Records",
    pregnancyCare: "Pregnancy Care",
    vaccination: "Vaccination",
    growthTracking: "Growth Tracking",
    yearsOld: "years old",
    healthcare: "Healthcare",
    addMember: "Add Member",
    addFamilyMember: "Add family member",
    newMember: "New Member",
    healthSetup: "Health Setup",
    
    chooseYourRole: "Choose Your Role",
    selectPatientOrDoctor: "Select whether you are a patient seeking care or a doctor providing care.",
    demoModeActive: "You're in demo mode - all features are fully functional without any setup!",
    experiencePatientJourney: "Experience the patient journey with full access to all healthcare features",
    exploreDoctorDashboard: "Explore the doctor dashboard with patient management and consultation tools",
    pregnancy: "Pregnancy",
    specializedPregnancyCare: "Specialized pregnancy care with diet plans, doctor appointments, and exercise reminders",
    pregnancyCareDesc: "Specialized care for expecting mothers",
    prenatalCare: "Prenatal Care",
    dietPlans: "Diet Plans",
    exercise: "Exercise",
    checkups: "Checkups",
    returnedToLogin: "Returned to login screen",
    
    settingUpKutumbhCare: "Setting up Kutumbh Care...",
    checkingDatabase: "Checking database",
    creatingDemoUsers: "Creating demo users",
    loggingYouIn: "Logging you in",
    onlyHappensOnce: "This only happens once - please wait...",
    
    databaseSetupRequired: "Database Setup Required",
    welcomeUserEmail: "Welcome {email}!",
    accountCreatedSuccessfully: "Your account was created successfully, but the database schema needs to be set up first. This is a one-time setup that takes about 2 minutes.",
    setupDatabaseNow: "Setup Database Now",
    signOutAndTryLater: "Sign Out and Try Later",
    databaseSetupOnlyOnce: "The database setup only needs to be done once by the first user",
    
    profileSetupIssue: "Profile Setup Issue",
    accountLabel: "Account: {email}",
    profileLoadingIssue: "Your account exists but your profile couldn't be loaded or created. This can happen if:",
    createdThroughDemoSetup: "You were created through demo setup",
    registrationIncomplete: "Your registration was incomplete",
    databasePermissionsIssue: "Database permissions issue",
    refreshProfile: "Refresh Profile",
    repairProfile: "Repair Profile",
    refreshAuthAndReload: "Refresh Auth & Reload",
    signOutAndTryAgain: "Sign Out and Try Again",
    persistsContactSupport: "If this persists, try using the demo login credentials or contact support",
    
    databaseConnectionIssue: "Database Connection Issue",
    unableToConnect: "Unable to connect to the database. Please check your connection and try again.",
    databaseSchemaNotSetup: "The database schema is not set up yet. Choose a setup method below.",
    quickFixRecommended: "Quick Fix (Recommended)",
    fullDatabaseSetup: "Full Database Setup",
    
    autoSetupComplete: "Auto-Setup Complete!",
    demoAccountsCreated: "Demo accounts were automatically created and you're now logged in as Demo Patient! Click on your user type above to continue.",
    autoCreatedPatient: "Auto-created: demo.patient@kutumbhcare.com",
    autoCreatedDoctor: "Auto-created: demo.doctor@kutumbhcare.com",
    autoLoggedIn: "Auto-logged in as Demo Patient",
    readyToSignIn: "Ready to sign in",
    
    demoSetupAvailable: "Demo Setup Available",
    demoAccountsReady: "Demo accounts are ready! You can sign in with the credentials below.",
    createDemoAccounts: "Create demo accounts to try out the app features. This is the recommended way to get started.",
    patientReady: "Patient: demo.patient@kutumbhcare.com (Ready)",
    doctorReady: "Doctor: demo.doctor@kutumbhcare.com (Ready)",
    createDemoUsers: "Create Demo Users",
    
    demoAccountsReadyToUse: "Demo accounts ready to use:",
    patientCredential: "Patient: demo.patient@kutumbhcare.com",
    doctorCredential: "Doctor: demo.doctor@kutumbhcare.com",
    passwordLabel: "Password:",
    passwordValue: "demo123",
    currentlyLoggedInDemo: "Currently logged in as Demo Patient",
    demoAccountCredentials: "Demo account credentials (create first):",
    createDemoUsersFirst: "Create demo users first before trying to sign in",
    
    database: "Database",
    demoUsers: "Demo Users",
    readyToUse: "Ready to Use",
    loggedIn: "Logged In",
    
    runDatabaseDiagnostics: "Run Database Diagnostics",
    quickDatabaseFix: "Quick Database Fix",
    databaseDiagnostics: "Database Diagnostics",
    connectionStatus: "Connection Status",
    connected: "Connected",
    notConnected: "Not Connected",
    rlsStatus: "RLS Status",
    active: "Active",
    notDetected: "Not Detected",
    tablesStatus: "Tables Status",
    found: "Found",
    missing: "Missing",
    exists: "Exists",
    diagnosticLog: "Diagnostic Log",
    errorLabel: "Error",
    close: "Close",
    
    runningDatabaseDiagnostics: "Running database diagnostics...",
    diagnosticsFailedError: "Diagnostics failed:",
    profileRefreshedSuccessfully: "Profile refreshed successfully",
    profileRefreshFailed: "Profile refresh failed:",
    profileRepairAttempted: "Profile repair attempted - refreshing...",
    profileRepairFailed: "Profile repair failed",
    authSessionRefreshed: "Auth session refreshed - reloading...",
    authRefreshFailed: "Auth refresh failed:",
    databaseFixApplied: "Database fix applied! The app should now work properly.",
    returnedToLoginScreen: "Returned to login screen",
    welcomeDemoPatient: "Welcome Demo Patient! Choose a family member to continue.",
    welcomeDemoDoctor: "Welcome Demo Doctor!",
    familyMemberAdded: "has been added to your family!",
    familyMemberRemoved: "has been removed from your family.",
    confirmRemoveFamilyMember: "Are you sure you want to remove {name} from your family?\\n\\nThis action cannot be undone and all their health records will be lost.",
    returnedToFamilySelection: "Returned to family member selection",
    
    spouse: "Spouse",
    parent: "Parent",
    sibling: "Sibling",
    grandparent: "Grandparent",
    otherFamilyMember: "Other Family Member",
    unknown: "Unknown",
    fillAllFields: "Please fill in all fields",
    validAgeRequired: "Please enter a valid age",
    back: "Back",
    addNewMember: "Add New Member",
    addMemberDesc: "Add a family member to manage their healthcare",
    fullName: "Full Name",
    enterFullName: "Enter full name",
    gender: "Gender",
    selectGender: "Select gender",
    male: "Male",
    female: "Female",
    enterAge: "Enter age",
    relationship: "Relationship",
    selectRelationship: "Select relationship",
    selectBloodGroup: "Select blood group",
    enablePregnancyCare: "Enable Pregnancy Care",
    familyMembersSavedLocally: "Family members will be saved locally on this device",
    
    welcomeBack: "Welcome back",
    chooseHealthcareService: "Choose a healthcare service",
    urgentMedicalAssistance: "Get urgent medical assistance 24/7",
    consultOnlineNow: "Consult with qualified doctors online",
    aiSymptomChecker: "AI-powered symptom analysis",
    speakYourSymptoms: "Speak your symptoms in your language",
    moreServices: "More Healthcare Services",
    recentActivity: "Recent Activity",
    consultationCompleted: "Consultation completed",
    hoursAgo: "hours ago",
    nextAppointment: "Next Appointment",
    drSinghCheckup: "Dr. Singh checkup scheduled",
    allDataSynced: "All data synced - Working offline ready",
    demoReady: "Demo Ready",
    
    pharmacyWallet: "Pharmacy Wallet",
    walletBalance: "Wallet Balance",
    balanceLow: "Balance is low",
    addMoney: "Add Money",
    addFunds: "Add Funds",
    enterAmount: "Enter Amount",
    enterValidAmount: "Please enter a valid amount",
    amountAdded: "added successfully",
    insufficientBalance: "Insufficient balance",
    outOfStock: "Out of Stock",
    purchaseSuccessful: "Purchase successful",
    downloadStatement: "Statement downloaded successfully",
    purchase: "Purchase",
    purchaseHistory: "Purchase History",
    monthlyStatement: "Monthly Statement",
    medicines: "Available Medicines",
    dosage: "Dosage",
    manufacturer: "Mfg",
    expiryDate: "Exp",
    inStock: "In Stock",
    buy: "Buy",
    availableBalance: "Available Balance",
    thisMonth: "This Month",
    totalExpenses: "Total Expenses",
    recentPurchases: "Recent Purchases",
    noTransactions: "No recent purchases",
    quantity: "Qty",
    price: "Price",
    transactionId: "TXN",
    medicineDetails: "Medicine Details",
    totalAmount: "Total",
    buyNow: "Buy Now",
    thisYear: "This Year",
    
    subscriptionPlans: "Subscription Plans",
    currentPlan: "Current Plan",
    planExpiry: "Plan Expiry",
    renewPlan: "Renew Plan",
    upgradePlan: "Upgrade Plan",
    basicPlan: "Basic Plan",
    premiumPlan: "Premium Plan",
    familyPlan: "Family Plan",
    monthlyBilling: "Monthly Billing",
    yearlyBilling: "Yearly Billing",
    savePercent: "Save 20%",
    planFeatures: "Plan Features",
    videoConsultations: "Video Consultations",
    aiDiagnostics: "AI Diagnostics",
    healthRecords: "Health Records",
    emergencySupport: "Emergency Support",
    familyMembers: "Family Members",
    prioritySupport: "Priority Support",
    paymentHistory: "Payment History",
    nextBilling: "Next Billing",
    manageSubscription: "Manage Subscription",
    cancelSubscription: "Cancel Subscription",
    paymentMethod: "Payment Method",
    cardNumber: "Card Number",
    expiryMonth: "Expiry Month",
    expiryYear: "Expiry Year",
    cvv: "CVV",
    cardholderName: "Cardholder Name",
    billingAddress: "Billing Address",
    payNow: "Pay Now",
    processingPayment: "Processing Payment...",
    paymentSuccessful: "Payment Successful",
    paymentFailed: "Payment Failed",
    subscriptionActive: "Subscription Active",
    subscriptionExpired: "Subscription Expired",
    freeTrialActive: "Free Trial Active",
    daysRemaining: "days remaining",
    unlimited: "Unlimited",
    limited: "Limited",
    notIncluded: "Not Included"
  },
  hi: {
    tagline: "ग्रामीण स्वास्थ्य सेवा को आसान बनाया गया",
    welcome: "स्वास्थ्य सेवा में आपका स्वागत है",
    welcomeDesc: "डॉक्टरों से जुड़ें, स्वास्थ्य रिकॉर्ड प्रबंधित करें, और चिकित्सा सहायता प्राप्त करें - सभी अपने गाँव से",
    patient: "मरीज़",
    doctor: "डॉक्टर",
    patientDesc: "चिकित्सा परामर्श प्राप्त करें और अपने स्वास्थ्य रिकॉर्ड प्रबंधित करें",
    doctorDesc: "रोगियों का प्रबंधन करें और टेली-परामर्श प्रदान करें",
    consultation: "वीडियो कॉल",
    records: "स्वास्थ्य कार्ड",
    symptomCheck: "एआई जांच",
    emergency: "आपातकाल",
    patients: "मेरे मरीज़",
    analytics: "रिपोर्ट",
    prescriptions: "दवाई",
    appointments: "अपॉइंटमेंट",
    poweredBy: "पंजाब सरकार स्वास्थ्य पहल",
    online: "ऑनलाइन",
    offline: "ऑफलाइन",
    
    myHealthCard: "मेरा स्वास्थ्य कार्ड",
    talkToDoctor: "डॉक्टर से बात करें",
    checkSymptoms: "लक्षण जांचें",
    emergencyHelp: "आपातकालीन सहायता",
    myMedicines: "मेरी दवाइयां",
    voiceHelp: "आवाज़ की सहायता",
    settings: "सेटिंग्स",
    
    callAmbulance: "एम्बुलेंस कॉल करें",
    nearestHospital: "निकटतम अस्पताल",
    policHelp: "पुलिस की सहायता",
    emergencyContacts: "आपातकालीन संपर्क",
    
    listening: "सुन रहे हैं...",
    tapToSpeak: "बोलने के लिए टैप करें",
    
    microphonePermissionTitle: "आवाज़ सुविधाएं सक्षम करें",
    microphonePermissionDesc: "नभा सिहता आपको नेविगेट करने और लक्षणों का वर्णन करने में मदद के लिए आवाज़ कमांड का उपयोग करता है। यह ऐप को उपयोग में आसान बनाता है, विशेषकर आपातकालीन स्थितियों के लिए।",
    allowMicrophone: "माइक्रोफ़ोन एक्सेस की अनुमति दें",
    continueWithoutVoice: "आवाज़ के बिना जारी रखें",
    microphoneSecurityNote: "आपका आवाज़ डेटा निजी रहता है और आपके डिवाइस पर स्थानीय रूप से प्रोसेस किया जाता है।",
    microphoneAccessGranted: "माइक्रोफ़ोन एक्सेस दी गई! आवाज़ सुविधाएं अब उपलब्ध हैं।",
    microphoneAccessDenied: "माइक्रोफ़ोन एक्सेस से इनकार। आवाज़ सुविधाएं काम नहीं करेंगी।",
    noMicrophoneFound: "कोई माइक्रोफ़ोन नहीं मिला। कृपया एक माइक्रोफ़ोन कनेक्ट करें।",
    microphoneNotSupported: "इस डिवाइस पर माइक्रोफ़ोन समर्थित नहीं है।",
    microphoneError: "माइक्रोफ़ोन एक्सेस करने में त्रुटि",
    httpsRequired: "आवाज़ सुविधाओं के लिए HTTPS कनेक्शन आवश्यक है",
    voiceFeaturesLimited: "माइक्रोफ़ोन एक्सेस के बिना आवाज़ सुविधाएं सीमित होंगी।",
    voiceEnabled: "आवाज़",
    voiceDisabled: "कोई आवाज़ नहीं",
    voiceUnknown: "आवाज़?",
    howToEnableVoice: "आवाज़ सुविधाएं कैसे सक्षम करें:",
    clickMicrophoneIcon: "अपने ब्राउज़र के पता बार में माइक्रोफ़ोन आइकन पर क्लिक करें",
    selectAllow: "माइक्रोफ़ोन एक्सेस के लिए 'अनुमति दें' चुनें",
    refreshIfNeeded: "यदि आवश्यक हो तो पेज रीफ्रेश करें",
    lookForMicIcon: "वेबसाइट पते के बगल में 🎤 या 🔒 आइकन देखें",
    
    patientId: "मरीज़ आईडी",
    age: "उम्र",
    bloodGroup: "ब्लड ग्रुप",
    allergies: "एलर्जी",
    medications: "वर्तमान दवाइयां",
    lastVisit: "अंतिम मुलाकात",
    
    findDoctor: "डॉक्टर खोजें",
    availableDoctors: "उपलब्ध डॉक्टर",
    startCall: "कॉल शुरू करें",
    
    describeSymptoms: "अपने लक्षणों का वर्णन करें",
    commonSymptoms: "सामान्य लक्षण",
    fever: "बुखार",
    cough: "खांसी",
    headache: "सिरदर्द",
    stomachPain: "पेट दर्द",
    
    todayAppointments: "आज की अपॉइंटमेंट्स",
    patientRecords: "मरीज़ रिकॉर्ड",
    prescriptionPad: "प्रिस्क्रिप्शन पैड",
    healthAnalytics: "स्वास्थ्य विश्लेषण",
    
    findHospitals: "अस्पताल खोजें",
    loading: "लोड हो रहा है",
    signOutSuccessful: "सफलतापूर्वक साइन आउट हो गए",
    demoAccountDesc: "बिना सेटअप के तुरंत सभी सुविधाओं का अनुभव करें",
    loginWelcomeDesc: "पंजाबी, हिंदी और अंग्रेजी में आवाज़ सहायता के साथ ग्रामीण समुदायों के लिए डिज़ाइन की गई स्वास्थ्य सेवाओं तक पहुंच।",
    
    chooseLoginMethod: "लॉगिन विधि चुनें",
    demoLogin: "डेमो लॉगिन",
    instantAccess: "तत्काल पहुंच, कोई सेटअप नहीं",
    signInWithAccount: "खाता के साथ साइन इन करें",
    forRegisteredUsers: "पंजीकृत उपयोगकर्ताओं के लिए",
    backToLogin: "लॉगिन पर वापस जाएं",
    chooseDemoProfile: "डेमो प्रोफ़ाइल चुनें",
    demoPatient: "डेमो मरीज़",
    demoDoctor: "डेमो डॉक्टर",
    familyHealthcareManagement: "पारिवारिक स्वास्थ्य प्रबंधन",
    healthcareProviderDashboard: "स्वास्थ्य प्रदाता डैशबोर्ड",
    family: "परिवार",
    patientPortal: "मरीज़ पोर्टल",
    noRegistrationRequired: "कोई पंजीकरण आवश्यक नहीं",
    fullFeatureAccess: "पूरी सुविधा पहुंच",
    worksOffline: "ऑफ़लाइन काम करता है",
    
    selectFamilyMember: "परिवार के सदस्य का चयन करें",
    chooseFamilyMemberDesc: "चुनें कि आज परिवार के किस सदस्य को स्वास्थ्य सेवाओं की आवश्यकता है।",
    personalizedHealthcareFeatures: "प्रत्येक सदस्य की व्यक्तिगत स्वास्थ्य सुविधाएं और रिकॉर्ड हैं",
    me: "मैं",
    wife: "पत्नी",
    child: "बच्चा",
    myHealthRecords: "मेरे स्वास्थ्य रिकॉर्ड",
    pregnancyCare: "गर्भावस्था देखभाल",
    vaccination: "टीकाकरण",
    growthTracking: "विकास ट्रैकिंग",
    yearsOld: "साल का",
    healthcare: "स्वास्थ्य सेवा",
    addMember: "सदस्य जोड़ें",
    addFamilyMember: "पारिवारिक सदस्य जोड़ें",
    newMember: "नया सदस्य",
    healthSetup: "स्वास्थ्य सेटअप",
    
    chooseYourRole: "अपनी भूमिका चुनें",
    selectPatientOrDoctor: "चुनें कि आप देखभाल चाहने वाले मरीज़ हैं या देखभाल प्रदान करने वाले डॉक्टर हैं।",
    demoModeActive: "आप डेमो मोड में हैं - सभी सुविधाएं बिना किसी सेटअप के पूरी तरह कार्यशील हैं!",
    experiencePatientJourney: "सभी स्वास्थ्य सुविधाओं तक पूरी पहुंच के साथ मरीज़ की यात्रा का अनुभव करें",
    exploreDoctorDashboard: "मरीज़ प्रबंधन और परामर्श उपकरणों के साथ डॉक्टर डैशबोर्ड का अन्वेषण करें",
    pregnancy: "गर्भावस्था",
    specializedPregnancyCare: "आहार योजनाओं, डॉक्टर अपॉइंटमेंट्स और व्यायाम रिमाइंडर के साथ विशेष गर्भावस्था देखभाल",
    pregnancyCareDesc: "गर्भवती माताओं के लिए विशेष देखभाल",
    prenatalCare: "जन्म से पहले की देखभाल",
    dietPlans: "आहार योजनाएं",
    exercise: "व्यायाम",
    checkups: "जांच",
    returnedToLogin: "लॉगिन स्क्रीन पर वापस आ गए",
    
    settingUpKutumbhCare: "नभा सिहता सेट अप कर रहे हैं...",
    checkingDatabase: "डेटाबेस जांच रहे हैं",
    creatingDemoUsers: "डेमो उपयोगकर्ता बना रहे हैं",
    loggingYouIn: "आपको लॉग इन कर रहे हैं",
    onlyHappensOnce: "यह केवल एक बार होता है - कृपया प्रतीक्षा करें...",
    
    databaseSetupRequired: "डेटाबेस सेटअप आवश्यक",
    welcomeUserEmail: "स्वागत {email}!",
    accountCreatedSuccessfully: "आपका खाता सफलतापूर्वक बनाया गया, लेकिन पहले डेटाबेस स्कीमा सेट अप करना होगा। यह एक बार का सेटअप है जिसमें लगभग 2 मिनट लगते हैं।",
    setupDatabaseNow: "अब डेटाबेस सेट अप करें",
    signOutAndTryLater: "साइन आउट करें और बाद में कोशिश करें",
    databaseSetupOnlyOnce: "डेटाबेस सेटअप केवल पहले उपयोगकर्ता द्वारा एक बार किया जाना चाहिए",
    
    profileSetupIssue: "प्रोफ़ाइल सेटअप समस्या",
    accountLabel: "खाता: {email}",
    profileLoadingIssue: "आपका खाता मौजूद है लेकिन आपकी प्रोफ़ाइल लोड या बनाई नहीं जा सकी। यह हो सकता है यदि:",
    createdThroughDemoSetup: "आप डेमो सेटअप के माध्यम से बनाए गए थे",
    registrationIncomplete: "आपका पंजीकरण अधूरा था",
    databasePermissionsIssue: "डेटाबेस अनुमतियों की समस्या",
    refreshProfile: "प्रोफ़ाइल रीफ्रेश करें",
    repairProfile: "प्रोफ़ाइल मरम्मत करें",
    refreshAuthAndReload: "ऑथ रीफ्रेश करें और रीलोड करें",
    signOutAndTryAgain: "साइन आउट करें और फिर कोशिश करें",
    persistsContactSupport: "यदि यह जारी रहता है, तो डेमो लॉगिन क्रेडेंशियल्स का उपयोग करने या सहायता से संपर्क करने का प्रयास करें",
    
    databaseConnectionIssue: "डेटाबेस कनेक्शन समस्या",
    unableToConnect: "डेटाबेस से कनेक्ट करने में असमर्थ। कृपया अपना कनेक्शन जांचें और फिर कोशिश करें।",
    databaseSchemaNotSetup: "डेटाबेस स्कीमा अभी तक सेट अप नहीं है। नीचे से सेटअप विधि चुनें।",
    quickFixRecommended: "त्वरित समाधान (अनुशंसित)",
    fullDatabaseSetup: "पूर्ण डेटाबेस सेटअप",
    
    autoSetupComplete: "ऑटो-सेटअप पूर्ण!",
    demoAccountsCreated: "डेमो खाते स्वचालित रूप से बनाए गए और आप अब डेमो मरीज़ के रूप में लॉग इन हैं! जारी रखने के लिए ऊपर अपना उपयोगकर्ता प्रकार चुनें।",
    autoCreatedPatient: "ऑटो-बनाया: demo.patient@kutumbhcare.com",
    autoCreatedDoctor: "ऑटो-बनाया: demo.doctor@kutumbhcare.com",
    autoLoggedIn: "डेमो मरीज़ के रूप में ऑटो-लॉग इन",
    readyToSignIn: "साइन इन के लिए तैयार",
    
    demoSetupAvailable: "डेमो सेटअप उपलब्ध",
    demoAccountsReady: "डेमो खाते तैयार हैं! आप नीचे दिए गए क्रेडेंशियल्स के साथ साइन इन कर सकते हैं।",
    createDemoAccounts: "ऐप सुविधाओं को आज़माने के लिए डेमो खाते बनाएं। यह शुरू करने का अनुशंसित तरीका है।",
    patientReady: "मरीज़: demo.patient@kutumbhcare.com (तैयार)",
    doctorReady: "डॉक्टर: demo.doctor@kutumbhcare.com (तैयार)",
    createDemoUsers: "डेमो उपयोगकर्ता बनाएं",
    
    demoAccountsReadyToUse: "उपयोग के लिए तैयार डेमो खाते:",
    patientCredential: "मरीज़: demo.patient@kutumbhcare.com",
    doctorCredential: "डॉक्टर: demo.doctor@kutumbhcare.com",
    passwordLabel: "पासवर्ड:",
    passwordValue: "demo123",
    currentlyLoggedInDemo: "वर्तमान में डेमो मरीज़ के रूप में लॉग इन",
    demoAccountCredentials: "डेमो खाता क्रेडेंशियल्स (पहले बनाएं):",
    createDemoUsersFirst: "साइन इन करने से पहले पहले डेमो उपयोगकर्ता बनाएं",
    
    database: "डेटाबेस",
    demoUsers: "डेमो उपयोगकर्ता",
    readyToUse: "उपयोग के लिए तैयार",
    loggedIn: "लॉग इन",
    
    runDatabaseDiagnostics: "डेटाबेस निदान चलाएं",
    quickDatabaseFix: "त्वरित डेटाबेस समाधान",
    databaseDiagnostics: "डेटाबेस निदान",
    connectionStatus: "कनेक्शन स्थिति",
    connected: "कनेक्टेड",
    notConnected: "कनेक्टेड नहीं",
    rlsStatus: "RLS स्थिति",
    active: "सक्रिय",
    notDetected: "पता नहीं चला",
    tablesStatus: "तालिकाओं की स्थिति",
    found: "मिला",
    missing: "गुम",
    exists: "मौजूद",
    diagnosticLog: "निदान लॉग",
    errorLabel: "त्रुटि",
    close: "बंद करें",
    
    runningDatabaseDiagnostics: "डेटाबेस निदान चला रहे हैं...",
    diagnosticsFailedError: "निदान असफल:",
    profileRefreshedSuccessfully: "प्रोफ़ाइल सफलतापूर्वक रीफ्रेश की गई",
    profileRefreshFailed: "प्रोफ़ाइल रीफ्रेश असफल:",
    profileRepairAttempted: "प्रोफ़ाइल मरम्मत का प्रयास किया गया - रीफ्रेश कर रहे हैं...",
    profileRepairFailed: "प्रोफ़ाइल मरम्मत असफल",
    authSessionRefreshed: "ऑथ सेशन रीफ्रेश किया गया - रीलोड कर रहे हैं...",
    authRefreshFailed: "ऑथ रीफ्रेश असफल:",
    databaseFixApplied: "डेटाबेस समाधान लागू किया गया! ऐप अब सही तरीके से काम करना चाहिए।",
    returnedToLoginScreen: "लॉगिन स्क्रीन पर वापस आ गए",
    welcomeDemoPatient: "डेमो मरीज़ का स्वागत! जारी रखने के लिए परिवार के सदस्य को चुनें।",
    welcomeDemoDoctor: "डेमो डॉक्टर का स्वागत!",
    familyMemberAdded: "आपके परिवार में जोड़ा गया है!",
    familyMemberRemoved: "आपके परिवार से हटा दिया गया है।",
    confirmRemoveFamilyMember: "क्या आप सच में {name} को अपने परिवार से हटाना चाहते हैं?\\n\\nयह कार्रवाई वापस नहीं की जा सकती और उनके सभी स्वास्थ्य रिकॉर्ड खो जाएंगे।",
    returnedToFamilySelection: "परिवार के सदस्य चयन पर वापस आ गए",
    
    spouse: "जीवनसाथी",
    parent: "माता-पिता",
    sibling: "भाई-बहन",
    grandparent: "दादा-दादी/नाना-नानी",
    otherFamilyMember: "अन्य पारिवारिक सदस्य",
    unknown: "अज्ञात",
    fillAllFields: "कृपया सभी फ़ील्ड भरें",
    validAgeRequired: "कृपया एक वैध उम्र दर्ज करें",
    back: "वापस",
    addNewMember: "नया सदस्य जोड़ें",
    addMemberDesc: "अपने परिवार के सदस्य को स्वास्थ्य सेवा प्रबंधन के लिए जोड़ें",
    fullName: "पूरा नाम",
    enterFullName: "पूरा नाम दर्ज करें",
    gender: "लिंग",
    selectGender: "लिंग चुनें",
    male: "पुरुष",
    female: "महिला",
    enterAge: "उम्र दर्ज करें",
    relationship: "रिश्ता",
    selectRelationship: "रिश्ता चुनें",
    selectBloodGroup: "ब्लड ग्रुप चुनें",
    enablePregnancyCare: "गर्भावस्था देखभाल सक्षम करें",
    familyMembersSavedLocally: "पारिवारिक सदस्य इस डिवाइस पर स्थानीय रूप से सेव होंगे",
    
    welcomeBack: "वापस आपका स्वागत है",
    chooseHealthcareService: "एक स्वास्थ्य सेवा चुनें",
    urgentMedicalAssistance: "24/7 तत्काल चिकित्सा सहायता प्राप्त करें",
    consultOnlineNow: "योग्य डॉक्टरों से ऑनलाइन सलाह लें",
    aiSymptomChecker: "AI-संचालित लक्षण विश्लेषण",
    speakYourSymptoms: "अपनी भाषा में अपने लक्षण बताएं",
    moreServices: "अधिक स्वास्थ्य सेवाएं",
    recentActivity: "हाल की गतिविधि",
    consultationCompleted: "परामर्श पूरा हुआ",
    hoursAgo: "घंटे पहले",
    nextAppointment: "अगली अपॉइंटमेंट",
    drSinghCheckup: "डॉ. सिंह की जांच निर्धारित",
    allDataSynced: "सभी डेटा सिंक हो गया - ऑफलाइन के लिए तैयार",
    demoReady: "डेमो तैयार",
    
    pharmacyWallet: "फार्मेसी वॉलेट",
    walletBalance: "वॉलेट बैलेंस",
    balanceLow: "बैलेंस कम है",
    addMoney: "पैसे जोड़ें",
    addFunds: "पैसे जोड़ें",
    enterAmount: "राशि दर्ज करें",
    enterValidAmount: "कृपया एक वैध राशि दर्ज करें",
    amountAdded: "सफलतापूर्वक जोड़ा गया",
    insufficientBalance: "अपर्याप्त बैलेंस",
    outOfStock: "स्टॉक में नहीं",
    purchaseSuccessful: "खरीदारी सफल",
    downloadStatement: "स्टेटमेंट सफलतापूर्वक डाउनलोड किया गया",
    purchase: "खरीदारी",
    purchaseHistory: "खरीदारी का इतिहास",
    monthlyStatement: "मासिक स्टेटमेंट",
    medicines: "उपलब्ध दवाइयां",
    dosage: "खुराक",
    manufacturer: "निर्माता",
    expiryDate: "समाप्ति तिथि",
    inStock: "स्टॉक में",
    buy: "खरीदें",
    availableBalance: "उपलब्ध बैलेंस",
    thisMonth: "इस महीने",
    totalExpenses: "कुल खर्च",
    recentPurchases: "हाल की खरीदारी",
    noTransactions: "कोई हाल की खरीदारी नहीं",
    quantity: "मात्रा",
    price: "कीमत",
    transactionId: "ट्रांजैक्शन आईडी",
    medicineDetails: "दवा का विवरण",
    totalAmount: "कुल राशि",
    buyNow: "अभी खरीदें",
    thisYear: "इस साल",
    
    subscriptionPlans: "सब्सक्रिप्शन प्लान",
    currentPlan: "वर्तमान प्लान",
    planExpiry: "प्लान समाप्ति",
    renewPlan: "प्लान नवीनीकरण",
    upgradePlan: "प्लान अपग्रेड",
    basicPlan: "बेसिक प्लान",
    premiumPlan: "प्रीमियम प्लान",
    familyPlan: "फैमिली प्लान",
    monthlyBilling: "मासिक बिलिंग",
    yearlyBilling: "वार्षिक बिलिंग",
    savePercent: "20% बचाएं",
    planFeatures: "प्लान की सुविधाएं",
    videoConsultations: "वीडियो परामर्श",
    aiDiagnostics: "AI निदान",
    healthRecords: "स्वास्थ्य रिकॉर्ड",
    emergencySupport: "आपातकालीन सहायता",
    familyMembers: "परिवार के सदस्य",
    prioritySupport: "प्राथमिकता सहायता",
    paymentHistory: "भुगतान का इतिहास",
    nextBilling: "अगली बिलिंग",
    manageSubscription: "सब्सक्रिप्शन प्रबंधन",
    cancelSubscription: "सब्सक्रिप्शन रद्द करें",
    paymentMethod: "भुगतान विधि",
    cardNumber: "कार्ड नंबर",
    expiryMonth: "समाप्ति महीना",
    expiryYear: "समाप्ति वर्ष",
    cvv: "सीवीवी",
    cardholderName: "कार्डधारक का नाम",
    billingAddress: "बिलिंग पता",
    payNow: "अभी भुगतान",
    processingPayment: "भुगतान प्रोसेसिंग...",
    paymentSuccessful: "भुगतान सफल",
    paymentFailed: "भुगतान असफल",
    subscriptionActive: "सब्सक्रिप्शन सक्रिय",
    subscriptionExpired: "सब्सक्रिप्शन समाप्त",
    freeTrialActive: "फ्री ट्रायल सक्रिय",
    daysRemaining: "दिन बचे",
    unlimited: "असीमित",
    limited: "सीमित",
    notIncluded: "शामिल नहीं"
  },
  pa: {
    tagline: "ਪੇਂਡੂ ਸਿਹਤ ਸੇਵਾ ਨੂੰ ਆਸਾਨ ਬਨਾਇਆ ਗਿਆ",
    welcome: "ਸਿਹਤ ਸੇਵਾ ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ",
    welcomeDesc: "ਡਾਕਟਰਾਂ ਨਾਲ ਜੁੜੋ, ਸਿਹਤ ਰਿਕਾਰਡ ਪ੍ਰਬੰਧਿਤ ਕਰੋ, ਅਤੇ ਡਾਕਟਰੀ ਮਦਦ ਲਓ - ਸਭ ਆਪਣੇ ਪਿੰਡ ਤੋਂ",
    patient: "ਮਰੀਜ਼",
    doctor: "ਡਾਕਟਰ",
    patientDesc: "ਡਾਕਟਰੀ ਸਲਾਹ ਲਓ ਅਤੇ ਆਪਣੇ ਸਿਹਤ ਰਿਕਾਰਡ ਪ੍ਰਬੰਧਿਤ ਕਰੋ",
    doctorDesc: "ਮਰੀਜ਼ਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ ਅਤੇ ਦੂਰ-ਸਲਾਹ ਦਿਓ",
    consultation: "ਵੀਡੀਓ ਕਾਲ",
    records: "ਸਿਹਤ ਕਾਰਡ",
    symptomCheck: "ਏਆਈ ਜਾਂਚ",
    emergency: "ਐਮਰਜੈਂਸੀ",
    patients: "ਮੇਰੇ ਮਰੀਜ਼",
    analytics: "ਰਿਪੋਰਟਾਂ",
    prescriptions: "ਦਵਾਈ",
    appointments: "ਮੁਲਾਕਾਤ",
    poweredBy: "ਪੰਜਾਬ ਸਰਕਾਰ ਸਿਹਤ ਪਹਿਲਕਦਮੀ",
    online: "ਔਨਲਾਈਨ",
    offline: "ਔਫਲਾਈਨ",
    
    myHealthCard: "ਮੇਰਾ ਸਿਹਤ ਕਾਰਡ",
    talkToDoctor: "ਡਾਕਟਰ ਨਾਲ ਗੱਲ ਕਰੋ",
    checkSymptoms: "ਲੱਛਣ ਜਾਂਚੋ",
    emergencyHelp: "ਐਮਰਜੈਂਸੀ ਮਦਦ",
    myMedicines: "ਮੇਰੀਆਂ ਦਵਾਈਆਂ",
    voiceHelp: "ਆਵਾਜ਼ ਦੀ ਮਦਦ",
    settings: "ਸੈਟਿੰਗਾਂ",
    
    callAmbulance: "ਐਂਬੂਲੈਂਸ ਬੁਲਾਓ",
    nearestHospital: "ਨੇੜਲਾ ਹਸਪਤਾਲ",
    policHelp: "ਪੁਲਿਸ ਦੀ ਮਦਦ",
    emergencyContacts: "ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ",
    
    listening: "ਸੁਣ ਰਹੇ ਹਾਂ...",
    tapToSpeak: "ਬੋਲਣ ਲਈ ਟੈਪ ਕਰੋ",
    
    microphonePermissionTitle: "ਆਵਾਜ਼ ਸੁਵਿਧਾਵਾਂ ਸਮਰੱਥ ਕਰੋ",
    microphonePermissionDesc: "ਨਭਾ ਸਿਹਤਾ ਤੁਹਾਨੂੰ ਨੈਵੀਗੇਟ ਕਰਨ ਅਤੇ ਲੱਛਣਾਂ ਦਾ ਵਰਣਨ ਕਰਨ ਵਿੱਚ ਮਦਦ ਲਈ ਆਵਾਜ਼ ਕਮਾਂਡਾਂ ਦੀ ਵਰਤੋਂ ਕਰਦਾ ਹੈ। ਇਹ ਐਪ ਨੂੰ ਵਰਤਣ ਵਿੱਚ ਆਸਾਨ ਬਣਾਉਂਦਾ ਹੈ, ਖਾਸ ਕਰਕੇ ਐਮਰਜੈਂਸੀ ਸਥਿਤੀਆਂ ਲਈ।",
    allowMicrophone: "ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਪਹੁੰਚ ਦੀ ਇਜਾਜ਼ਤ ਦਿਓ",
    continueWithoutVoice: "ਆਵਾਜ਼ ਤੋਂ ਬਿਨਾਂ ਜਾਰੀ ਰੱਖੋ",
    microphoneSecurityNote: "ਤੁਹਾਡਾ ਆਵਾਜ਼ ਡੇਟਾ ਨਿੱਜੀ ਰਹਿੰਦਾ ਹੈ ਅਤੇ ਤੁਹਾਡੇ ਡਿਵਾਈਸ 'ਤੇ ਸਥਾਨਕ ਰੂਪ ਵਿੱਚ ਪ੍ਰੋਸੈਸ ਕੀਤਾ ਜਾਂਦਾ ਹੈ।",
    microphoneAccessGranted: "ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਪਹੁੰਚ ਮਿਲੀ! ਆਵਾਜ਼ ਸੁਵਿਧਾਵਾਂ ਹੁਣ ਉਪਲਬਧ ਹਨ।",
    microphoneAccessDenied: "ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਪਹੁੰਚ ਤੋਂ ਇਨਕਾਰ। ਆਵਾਜ਼ ਸੁਵਿਧਾਵਾਂ ਕੰਮ ਨਹੀਂ ਕਰਨਗੀਆਂ।",
    noMicrophoneFound: "ਕੋਈ ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਨਹੀਂ ਮਿਲਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਕਨੈਕਟ ਕਰੋ।",
    microphoneNotSupported: "ਇਸ ਡਿਵਾਈਸ 'ਤੇ ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਸਮਰਥਿਤ ਨਹੀਂ।",
    microphoneError: "ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਤੱਕ ਪਹੁੰਚ ਵਿੱਚ ਗਲਤੀ",
    httpsRequired: "ਆਵਾਜ਼ ਸੁਵਿਧਾਵਾਂ ਲਈ HTTPS ਕਨੈਕਸ਼ਨ ਲੋੜੀਂਦਾ ਹੈ",
    voiceFeaturesLimited: "ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਪਹੁੰਚ ਤੋਂ ਬਿਨਾਂ ਆਵਾਜ਼ ਸੁਵਿਧਾਵਾਂ ਸੀਮਿਤ ਹੋਣਗੀਆਂ।",
    voiceEnabled: "ਆਵਾਜ਼",
    voiceDisabled: "ਕੋਈ ਆਵਾਜ਼ ਨਹੀਂ",
    voiceUnknown: "ਆਵਾਜ਼?",
    howToEnableVoice: "ਆਵਾਜ਼ ਸੁਵਿਧਾਵਾਂ ਕਿਵੇਂ ਸਮਰੱਥ ਕਰੀਏ:",
    clickMicrophoneIcon: "ਆਪਣੇ ਬ੍ਰਾਉਜ਼ਰ ਦੇ ਪਤਾ ਬਾਰ ਵਿੱਚ ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਆਈਕਨ 'ਤੇ ਕਲਿੱਕ ਕਰੋ",
    selectAllow: "ਮਾਈਕ੍ਰੋਫ਼ੋਨ ਪਹੁੰਚ ਲਈ 'ਇਜਾਜ਼ਤ ਦਿਓ' ਚੁਣੋ",
    refreshIfNeeded: "ਜੇ ਲੋੜ ਹੋਵੇ ਤਾਂ ਪੰਨਾ ਰੀਫ੍ਰੈਸ਼ ਕਰੋ",
    lookForMicIcon: "ਵੈਬਸਾਈਟ ਪਤੇ ਦੇ ਨਾਲ 🎤 ਜਾਂ 🔒 ਆਈਕਨ ਦੇਖੋ",
    
    patientId: "ਮਰੀਜ਼ ਆਈਡੀ",
    age: "ਉਮਰ",
    bloodGroup: "ਬਲੱਡ ਗਰੁੱਪ",
    allergies: "ਐਲਰਜੀ",
    medications: "ਮੌਜੂਦਾ ਦਵਾਈਆਂ",
    lastVisit: "ਆਖਰੀ ਮੁਲਾਕਾਤ",
    
    findDoctor: "ਡਾਕਟਰ ਲੱਭੋ",
    availableDoctors: "ਉਪਲਬਧ ਡਾਕਟਰ",
    startCall: "ਕਾਲ ਸ਼ੁਰੂ ਕਰੋ",
    
    describeSymptoms: "ਆਪਣੇ ਲੱਛਣਾਂ ਦਾ ਵਰਣਨ ਕਰੋ",
    commonSymptoms: "ਆਮ ਲੱਛਣ",
    fever: "ਬੁਖਾਰ",
    cough: "ਖੰਘ",
    headache: "ਸਿਰਦਰਦ",
    stomachPain: "ਪੇਟ ਦਰਦ",
    
    todayAppointments: "ਅੱਜ ਦੀਆਂ ਮੁਲਾਕਾਤਾਂ",
    patientRecords: "ਮਰੀਜ਼ ਰਿਕਾਰਡ",
    prescriptionPad: "ਪ੍ਰਿਸਕ੍ਰਿਪਸ਼ਨ ਪੈਡ",
    healthAnalytics: "ਸਿਹਤ ਵਿਸ਼ਲੇਸ਼ਣ",
    
    findHospitals: "ਹਸਪਤਾਲ ਲੱਭੋ",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ",
    signOutSuccessful: "ਸਫਲਤਾਪੂਰਵਕ ਸਾਈਨ ਆਊਟ ਹੋ ਗਏ",
    demoAccountDesc: "ਬਿਨਾਂ ਸੈਟਅਪ ਦੇ ਤੁਰੰਤ ਸਾਰੀਆਂ ਸੁਵਿਧਾਵਾਂ ਦਾ ਅਨੁਭਵ ਕਰੋ",
    loginWelcomeDesc: "ਪੰਜਾਬੀ, ਹਿੰਦੀ ਅਤੇ ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ ਆਵਾਜ਼ ਸਹਾਇਤਾ ਦੇ ਨਾਲ ਪੇਂਡੂ ਭਾਈਚਾਰਿਆਂ ਲਈ ਡਿਜ਼ਾਈਨ ਕੀਤੀਆਂ ਸਿਹਤ ਸੇਵਾਵਾਂ ਤੱਕ ਪਹੁੰਚ।",
    
    chooseLoginMethod: "ਲਾਗਇਨ ਵਿਧੀ ਚੁਣੋ",
    demoLogin: "ਡੈਮੋ ਲਾਗਇਨ",
    instantAccess: "ਤੁਰੰਤ ਪਹੁੰਚ, ਕੋਈ ਸੈਟਅਪ ਨਹੀਂ",
    signInWithAccount: "ਅਕਾਊਂਟ ਨਾਲ ਸਾਈਨ ਇਨ ਕਰੋ",
    forRegisteredUsers: "ਰਜਿਸਟਰਡ ਉਪਭੋਗਤਾਵਾਂ ਲਈ",
    backToLogin: "ਲਾਗਇਨ 'ਤੇ ਵਾਪਸ ਜਾਓ",
    chooseDemoProfile: "ਡੈਮੋ ਪ੍ਰੋਫਾਈਲ ਚੁਣੋ",
    demoPatient: "ਡੈਮੋ ਮਰੀਜ਼",
    demoDoctor: "ਡੈਮੋ ਡਾਕਟਰ",
    familyHealthcareManagement: "ਪਰਿਵਾਰਕ ਸਿਹਤ ਪ੍ਰਬੰਧਨ",
    healthcareProviderDashboard: "ਸਿਹਤ ਪ੍ਰਦਾਤਾ ਡੈਸ਼ਬੋਰਡ",
    family: "ਪਰਿਵਾਰ",
    patientPortal: "ਮਰੀਜ਼ ਪੋਰਟਲ",
    noRegistrationRequired: "ਕੋਈ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਲੋੜੀਂਦੀ ਨਹੀਂ",
    fullFeatureAccess: "ਪੂਰੀ ਸੁਵਿਧਾ ਪਹੁੰਚ",
    worksOffline: "ਔਫਲਾਈਨ ਕੰਮ ਕਰਦਾ ਹੈ",
    
    selectFamilyMember: "ਪਰਿਵਾਰ ਦੇ ਮੈਂਬਰ ਨੂੰ ਚੁਣੋ",
    chooseFamilyMemberDesc: "ਚੁਣੋ ਕਿ ਅੱਜ ਪਰਿਵਾਰ ਦੇ ਕਿਸ ਮੈਂਬਰ ਨੂੰ ਸਿਹਤ ਸੇਵਾਵਾਂ ਦੀ ਲੋੜ ਹੈ।",
    personalizedHealthcareFeatures: "ਹਰੇਕ ਮੈਂਬਰ ਦੀਆਂ ਵਿਅਕਤੀਗਤ ਸਿਹਤ ਸੁਵਿਧਾਵਾਂ ਅਤੇ ਰਿਕਾਰਡ ਹਨ",
    me: "ਮੈਂ",
    wife: "ਪਤਨੀ",
    child: "ਬੱਚਾ",
    myHealthRecords: "ਮੇਰੇ ਸਿਹਤ ਰਿਕਾਰਡ",
    pregnancyCare: "ਗਰਭਾਵਸਥਾ ਦੇਖਭਾਲ",
    vaccination: "ਟੀਕਾਕਰਣ",
    growthTracking: "ਵਿਕਾਸ ਟਰੈਕਿੰਗ",
    yearsOld: "ਸਾਲ ਦਾ",
    healthcare: "ਸਿਹਤ ਸੇਵਾ",
    addMember: "ਮੈਂਬਰ ਜੋੜੋ",
    addFamilyMember: "ਪਰਿਵਾਰਕ ਮੈਂਬਰ ਜੋੜੋ",
    newMember: "ਨਵਾਂ ਮੈਂਬਰ",
    healthSetup: "ਸਿਹਤ ਸੈਟਅਪ",
    
    chooseYourRole: "ਆਪਣੀ ਭੂਮਿਕਾ ਚੁਣੋ",
    selectPatientOrDoctor: "ਚੁਣੋ ਕਿ ਤੁਸੀਂ ਦੇਖਭਾਲ ਚਾਹਣ ਵਾਲੇ ਮਰੀਜ਼ ਹੋ ਜਾਂ ਦੇਖਭਾਲ ਪ੍ਰਦਾਨ ਕਰਨ ਵਾਲੇ ਡਾਕਟਰ ਹੋ।",
    demoModeActive: "ਤੁਸੀਂ ਡੈਮੋ ਮੋਡ ਵਿੱਚ ਹੋ - ਸਾਰੀਆਂ ਸੁਵਿਧਾਵਾਂ ਬਿਨਾਂ ਕਿਸੇ ਸੈਟਅਪ ਦੇ ਪੂਰੀ ਤਰ੍ਹਾਂ ਕਾਰਜਸ਼ੀਲ ਹਨ!",
    experiencePatientJourney: "ਸਾਰੀਆਂ ਸਿਹਤ ਸੁਵਿਧਾਵਾਂ ਤੱਕ ਪੂਰੀ ਪਹੁੰਚ ਦੇ ਨਾਲ ਮਰੀਜ਼ ਦੀ ਯਾਤਰਾ ਦਾ ਅਨੁਭਵ ਕਰੋ",
    exploreDoctorDashboard: "ਮਰੀਜ਼ ਪ੍ਰਬੰਧਨ ਅਤੇ ਸਲਾਹ ਟੂਲਸ ਦੇ ਨਾਲ ਡਾਕਟਰ ਡੈਸ਼ਬੋਰਡ ਦੀ ਖੋਜ ਕਰੋ",
    pregnancy: "ਗਰਭਾਵਸਥਾ",
    specializedPregnancyCare: "ਖੁਰਾਕ ਯੋਜਨਾਵਾਂ, ਡਾਕਟਰ ਮੁਲਾਕਾਤਾਂ ਅਤੇ ਕਸਰਤ ਰਿਮਾਈਂਡਰਾਂ ਦੇ ਨਾਲ ਵਿਸ਼ੇਸ਼ ਗਰਭਾਵਸਥਾ ਦੇਖਭਾਲ",
    pregnancyCareDesc: "ਗਰਭਵਤੀ ਮਾਵਾਂ ਲਈ ਵਿਸ਼ੇਸ਼ ਦੇਖਭਾਲ",
    prenatalCare: "ਜਨਮ ਤੋਂ ਪਹਿਲਾਂ ਦੀ ਦੇਖਭਾਲ",
    dietPlans: "ਖੁਰਾਕ ਯੋਜਨਾਵਾਂ",
    exercise: "ਕਸਰਤ",
    checkups: "ਜਾਂਚਾਂ",
    returnedToLogin: "ਲਾਗਇਨ ਸਕ੍ਰੀਨ 'ਤੇ ਵਾਪਸ ਆ ਗਏ",
    
    settingUpKutumbhCare: "ਨਭਾ ਸਿਹਤਾ ਸੈਟ ਅਪ ਕਰ ਰਹੇ ਹਾਂ...",
    checkingDatabase: "ਡੇਟਾਬੇਸ ਜਾਂਚ ਰਹੇ ਹਾਂ",
    creatingDemoUsers: "ਡੈਮੋ ਉਪਭੋਗਤਾ ਬਣਾ ਰਹੇ ਹਾਂ",
    loggingYouIn: "ਤੁਹਾਨੂੰ ਲਾਗ ਇਨ ਕਰ ਰਹੇ ਹਾਂ",
    onlyHappensOnce: "ਇਹ ਕੇਵਲ ਇੱਕ ਵਾਰ ਹੁੰਦਾ ਹੈ - ਕਿਰਪਾ ਕਰਕੇ ਉਡੀਕ ਕਰੋ...",
    
    databaseSetupRequired: "ਡੇਟਾਬੇਸ ਸੈਟਅਪ ਲੋੜੀਂਦਾ",
    welcomeUserEmail: "ਸਵਾਗਤ {email}!",
    accountCreatedSuccessfully: "ਤੁਹਾਡਾ ਅਕਾਊਂਟ ਸਫਲਤਾਪੂਰਵਕ ਬਣਾਇਆ ਗਿਆ, ਪਰ ਪਹਿਲਾਂ ਡੇਟਾਬੇਸ ਸਕੀਮਾ ਸੈਟ ਅਪ ਕਰਨਾ ਹੋਗਾ। ਇਹ ਇੱਕ ਵਾਰ ਦਾ ਸੈਟਅਪ ਹੈ ਜਿਸ ਵਿੱਚ ਲਗਭਗ 2 ਮਿੰਟ ਲੱਗਦੇ ਹਨ।",
    setupDatabaseNow: "ਹੁਣ ਡੇਟਾਬੇਸ ਸੈਟ ਅਪ ਕਰੋ",
    signOutAndTryLater: "ਸਾਈਨ ਆਊਟ ਕਰੋ ਅਤੇ ਬਾਅਦ ਵਿੱਚ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
    databaseSetupOnlyOnce: "ਡੇਟਾਬੇਸ ਸੈਟਅਪ ਕੇਵਲ ਪਹਿਲੇ ਉਪਭੋਗਤਾ ਦੁਆਰਾ ਇੱਕ ਵਾਰ ਕੀਤਾ ਜਾਣਾ ਚਾਹੀਦਾ ਹੈ",
    
    profileSetupIssue: "ਪ੍ਰੋਫਾਈਲ ਸੈਟਅਪ ਸਮੱਸਿਆ",
    accountLabel: "ਅਕਾਊਂਟ: {email}",
    profileLoadingIssue: "ਤੁਹਾਡਾ ਅਕਾਊਂਟ ਮੌਜੂਦ ਹੈ ਪਰ ਤੁਹਾਡੀ ਪ੍ਰੋਫਾਈਲ ਲੋਡ ਜਾਂ ਬਣਾਈ ਨਹੀਂ ਜਾ ਸਕੀ। ਇਹ ਹੋ ਸਕਦਾ ਹੈ ਜੇ:",
    createdThroughDemoSetup: "ਤੁਸੀਂ ਡੈਮੋ ਸੈਟਅਪ ਰਾਹੀਂ ਬਣਾਏ ਗਏ ਸੀ",
    registrationIncomplete: "ਤੁਹਾਡਾ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਅਧੂਰਾ ਸੀ",
    databasePermissionsIssue: "ਡੇਟਾਬੇਸ ਇਜਾਜ਼ਤਾਂ ਦੀ ਸਮੱਸਿਆ",
    refreshProfile: "ਪ੍ਰੋਫਾਈਲ ਰਿਫਰੈਸ਼ ਕਰੋ",
    repairProfile: "ਪ੍ਰੋਫਾਈਲ ਮਰੰਮਤ ਕਰੋ",
    refreshAuthAndReload: "ਔਥ ਰਿਫਰੈਸ਼ ਕਰੋ ਅਤੇ ਰੀਲੋਡ ਕਰੋ",
    signOutAndTryAgain: "ਸਾਈਨ ਆਊਟ ਕਰੋ ਅਤੇ ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
    persistsContactSupport: "ਜੇ ਇਹ ਜਾਰੀ ਰਹਿੰਦਾ ਹੈ, ਤਾਂ ਡੈਮੋ ਲਾਗਇਨ ਕ੍ਰੀਡੈਂਸ਼ੀਅਲਜ਼ ਦੀ ਵਰਤੋਂ ਕਰਨ ਜਾਂ ਸਹਾਇਤਾ ਨਾਲ ਸੰਪਰਕ ਕਰਨ ਦੀ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
    
    databaseConnectionIssue: "ਡੇਟਾਬੇਸ ਕਨੈਕਸ਼ਨ ਸਮੱਸਿਆ",
    unableToConnect: "ਡੇਟਾਬੇਸ ਨਾਲ ਕਨੈਕਟ ਕਰਨ ਵਿੱਚ ਅਸਮਰੱਥ। ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਕਨੈਕਸ਼ਨ ਜਾਂਚੋ ਅਤੇ ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    databaseSchemaNotSetup: "ਡੇਟਾਬੇਸ ਸਕੀਮਾ ਅਜੇ ਸੈਟ ਅਪ ਨਹੀਂ ਹੈ। ਹੇਠਾਂ ਤੋਂ ਸੈਟਅਪ ਵਿਧੀ ਚੁਣੋ।",
    quickFixRecommended: "ਤੇਜ਼ ਸਮਾਧਾਨ (ਸਿਫਾਰਸ਼ਿਤ)",
    fullDatabaseSetup: "ਪੂਰਾ ਡੇਟਾਬੇਸ ਸੈਟਅਪ",
    
    autoSetupComplete: "ਆਟੋ-ਸੈਟਅਪ ਪੂਰਾ!",
    demoAccountsCreated: "ਡੈਮੋ ਅਕਾਊਂਟਸ ਆਪਣੇ ਆਪ ਬਣਾਏ ਗਏ ਅਤੇ ਤੁਸੀਂ ਹੁਣ ਡੈਮੋ ਮਰੀਜ਼ ਦੇ ਰੂਪ ਵਿੱਚ ਲਾਗ ਇਨ ਹੋ! ਜਾਰੀ ਰੱਖਣ ਲਈ ਉੱਪਰ ਆਪਣਾ ਉਪਭੋਗਤਾ ਕਿਸਮ ਚੁਣੋ।",
    autoCreatedPatient: "ਆਟੋ-ਬਣਾਇਆ: demo.patient@kutumbhcare.com",
    autoCreatedDoctor: "ਆਟੋ-ਬਣਾਇਆ: demo.doctor@kutumbhcare.com",
    autoLoggedIn: "ਡੈਮੋ ਮਰੀਜ਼ ਦੇ ਰੂਪ ਵਿੱਚ ਆਟੋ-ਲਾਗ ਇਨ",
    readyToSignIn: "ਸਾਈਨ ਇਨ ਲਈ ਤਿਆਰ",
    
    demoSetupAvailable: "ਡੈਮੋ ਸੈਟਅਪ ਉਪਲਬਧ",
    demoAccountsReady: "ਡੈਮੋ ਅਕਾਊਂਟਸ ਤਿਆਰ ਹਨ! ਤੁਸੀਂ ਹੇਠਾਂ ਦਿੱਤੇ ਕ੍ਰੀਡੈਂਸ਼ੀਅਲਜ਼ ਨਾਲ ਸਾਈਨ ਇਨ ਕਰ ਸਕਦੇ ਹੋ।",
    createDemoAccounts: "ਐਪ ਸੁਵਿਧਾਵਾਂ ਨੂੰ ਅਜ਼ਮਾਉਣ ਲਈ ਡੈਮੋ ਅਕਾਊਂਟਸ ਬਣਾਓ। ਇਹ ਸ਼ੁਰੂ ਕਰਨ ਦਾ ਸਿਫਾਰਸ਼ਿਤ ਤਰੀਕਾ ਹੈ।",
    patientReady: "ਮਰੀਜ਼: demo.patient@kutumbhcare.com (ਤਿਆਰ)",
    doctorReady: "ਡਾਕਟਰ: demo.doctor@kutumbhcare.com (ਤਿਆਰ)",
    createDemoUsers: "ਡੈਮੋ ਉਪਭੋਗਤਾ ਬਣਾਓ",
    
    demoAccountsReadyToUse: "ਵਰਤੋਂ ਲਈ ਤਿਆਰ ਡੈਮੋ ਅਕਾਊਂਟਸ:",
    patientCredential: "ਮਰੀਜ਼: demo.patient@kutumbhcare.com",
    doctorCredential: "ਡਾਕਟਰ: demo.doctor@kutumbhcare.com",
    passwordLabel: "ਪਾਸਵਰਡ:",
    passwordValue: "demo123",
    currentlyLoggedInDemo: "ਵਰਤਮਾਨ ਵਿੱਚ ਡੈਮੋ ਮਰੀਜ਼ ਦੇ ਰੂਪ ਵਿੱਚ ਲਾਗ ਇਨ",
    demoAccountCredentials: "ਡੈਮੋ ਅਕਾਊਂਟ ਕ੍ਰੀਡੈਂਸ਼ੀਅਲਜ਼ (ਪਹਿਲਾਂ ਬਣਾਓ):",
    createDemoUsersFirst: "ਸਾਈਨ ਇਨ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਪਹਿਲਾਂ ਡੈਮੋ ਉਪਭੋਗਤਾ ਬਣਾਓ",
    
    database: "ਡੇਟਾਬੇਸ",
    demoUsers: "ਡੈਮੋ ਉਪਭੋਗਤਾ",
    readyToUse: "ਵਰਤੋਂ ਲਈ ਤਿਆਰ",
    loggedIn: "ਲਾਗ ਇਨ",
    
    runDatabaseDiagnostics: "ਡੇਟਾਬੇਸ ਨਿਦਾਨ ਚਲਾਓ",
    quickDatabaseFix: "ਤੇਜ਼ ਡੇਟਾਬੇਸ ਸਮਾਧਾਨ",
    databaseDiagnostics: "ਡੇਟਾਬੇਸ ਨਿਦਾਨ",
    connectionStatus: "ਕਨੈਕਸ਼ਨ ਸਥਿਤੀ",
    connected: "ਕਨੈਕਟਿਡ",
    notConnected: "ਕਨੈਕਟਿਡ ਨਹੀਂ",
    rlsStatus: "RLS ਸਥਿਤੀ",
    active: "ਸਰਗਰਮ",
    notDetected: "ਪਤਾ ਨਹੀਂ ਚਲਾ",
    tablesStatus: "ਟੇਬਲਾਂ ਦੀ ਸਥਿਤੀ",
    found: "ਮਿਲਿਆ",
    missing: "ਗੁੰਮ",
    exists: "ਮੌਜੂਦ",
    diagnosticLog: "ਨਿਦਾਨ ਲਾਗ",
    errorLabel: "ਗਲਤੀ",
    close: "ਬੰਦ ਕਰੋ",
    
    runningDatabaseDiagnostics: "ਡੇਟਾਬੇਸ ਨਿਦਾਨ ਚਲਾ ਰਹੇ ਹਾਂ...",
    diagnosticsFailedError: "ਨਿਦਾਨ ਅਸਫਲ:",
    profileRefreshedSuccessfully: "ਪ੍ਰੋਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਰਿਫਰੈਸ਼ ਕੀਤੀ ਗਈ",
    profileRefreshFailed: "ਪ੍ਰੋਫਾਈਲ ਰਿਫਰੈਸ਼ ਅਸਫਲ:",
    profileRepairAttempted: "ਪ੍ਰੋਫਾਈਲ ਮਰੰਮਤ ਦੀ ਕੋਸ਼ਿਸ਼ ਕੀਤੀ ਗਈ - ਰਿਫਰੈਸ਼ ਕਰ ਰਹੇ ਹਾਂ...",
    profileRepairFailed: "ਪ੍ਰੋਫਾਈਲ ਮਰੰਮਤ ਅਸਫਲ",
    authSessionRefreshed: "ਔਥ ਸੈਸ਼ਨ ਰਿਫਰੈਸ਼ ਕੀਤਾ ਗਿਆ - ਰੀਲੋਡ ਕਰ ਰਹੇ ਹਾਂ...",
    authRefreshFailed: "ਔਥ ਰਿਫਰੈਸ਼ ਅਸਫਲ:",
    databaseFixApplied: "ਡੇਟਾਬੇਸ ਸਮਾਧਾਨ ਲਾਗੂ ਕੀਤਾ ਗਿਆ! ਐਪ ਅੱਜ ਸਹੀ ਤਰ੍ਹਾਂ ਕੰਮ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ।",
    returnedToLoginScreen: "ਲਾਗਇਨ ਸਕ੍ਰੀਨ 'ਤੇ ਵਾਪਸ ਆ ਗਏ",
    welcomeDemoPatient: "ਡੈਮੋ ਮਰੀਜ਼ ਦਾ ਸਵਾਗਤ! ਜਾਰੀ ਰੱਖਣ ਲਈ ਪਰਿਵਾਰ ਦੇ ਮੈਂਬਰ ਨੂੰ ਚੁਣੋ।",
    welcomeDemoDoctor: "ਡੈਮੋ ਡਾਕਟਰ ਦਾ ਸਵਾਗਤ!",
    familyMemberAdded: "ਤੁਹਾਡੇ ਪਰਿਵਾਰ ਵਿੱਚ ਜੋੜਿਆ ਗਿਆ ਹੈ!",
    familyMemberRemoved: "ਤੁਹਾਡੇ ਪਰਿਵਾਰ ਤੋਂ ਹਟਾ ਦਿੱਤਾ ਗਿਆ ਹੈ।",
    confirmRemoveFamilyMember: "ਕੀ ਤੁਸੀਂ ਸੱਚਮੁੱਚ {name} ਨੂੰ ਆਪਣੇ ਪਰਿਵਾਰ ਤੋਂ ਹਟਾਉਣਾ ਚਾਹੁੰਦੇ ਹੋ?\\n\\nਇਹ ਕਾਰਵਾਈ ਵਾਪਸ ਨਹੀਂ ਕੀਤੀ ਜਾ ਸਕਦੀ ਅਤੇ ਉਨ੍ਹਾਂ ਦੇ ਸਾਰੇ ਸਿਹਤ ਰਿਕਾਰਡ ਗੁਆਚ ਜਾਣਗੇ।",
    returnedToFamilySelection: "ਪਰਿਵਾਰ ਦੇ ਮੈਂਬਰ ਚੋਣ 'ਤੇ ਵਾਪਸ ਆ ਗਏ",
    
    spouse: "ਜੀਵਨ ਸਾਥੀ",
    parent: "ਮਾਤਾ-ਪਿਤਾ",
    sibling: "ਭਰਾ-ਭੈਣ",
    grandparent: "ਦਾਦਾ-ਦਾਦੀ/ਨਾਨਾ-ਨਾਨੀ",
    otherFamilyMember: "ਹੋਰ ਪਰਿਵਾਰਿਕ ਮੈਂਬਰ",
    unknown: "ਅਣਜਾਣ",
    fillAllFields: "ਕਿਰਪਾ ਕਰਕੇ ਸਾਰੇ ਖੇਤਰ ਭਰੋ",
    validAgeRequired: "ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ ਉਮਰ ਦਰਜ ਕਰੋ",
    back: "ਵਾਪਸ",
    addNewMember: "ਨਵਾਂ ਮੈਂਬਰ ਜੋੜੋ",
    addMemberDesc: "ਆਪਣੇ ਪਰਿਵਾਰ ਦੇ ਮੈਂਬਰ ਨੂੰ ਸਿਹਤ ਸੇਵਾ ਪ੍ਰਬੰਧਨ ਲਈ ਜੋੜੋ",
    fullName: "ਪੂਰਾ ਨਾਮ",
    enterFullName: "ਪੂਰਾ ਨਾਮ ਦਰਜ ਕਰੋ",
    gender: "ਲਿੰਗ",
    selectGender: "ਲਿੰਗ ਚੁਣੋ",
    male: "ਮਰਦ",
    female: "ਔਰਤ",
    enterAge: "ਉਮਰ ਦਰਜ ਕਰੋ",
    relationship: "ਰਿਸ਼ਤਾ",
    selectRelationship: "ਰਿਸ਼ਤਾ ਚੁਣੋ",
    selectBloodGroup: "ਬਲੱਡ ਗਰੁੱਪ ਚੁਣੋ",
    enablePregnancyCare: "ਗਰਭਾਵਸਥਾ ਦੇਖਭਾਲ ਸਮਰੱਥ ਕਰੋ",
    familyMembersSavedLocally: "ਪਰਿਵਾਰਿਕ ਮੈਂਬਰ ਇਸ ਡਿਵਾਈਸ 'ਤੇ ਸਥਾਨਕ ਰੂਪ ਵਿੱਚ ਸੇਵ ਹੋਣਗੇ",
    
    welcomeBack: "ਵਾਪਸ ਜੀ ਆਇਆਂ ਨੂੰ",
    chooseHealthcareService: "ਇੱਕ ਸਿਹਤ ਸੇਵਾ ਚੁਣੋ",
    urgentMedicalAssistance: "24/7 ਤੁਰੰਤ ਡਾਕਟਰੀ ਮਦਦ ਲਓ",
    consultOnlineNow: "ਯੋਗ ਡਾਕਟਰਾਂ ਨਾਲ ਔਨਲਾਈਨ ਸਲਾਹ ਲਓ",
    aiSymptomChecker: "ਏਆਈ-ਸੰਚਾਲਿਤ ਲੱਛਣ ਵਿਸ਼ਲੇਸ਼ਣ",
    speakYourSymptoms: "ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਆਪਣੇ ਲੱਛਣ ਦੱਸੋ",
    moreServices: "ਹੋਰ ਸਿਹਤ ਸੇਵਾਵਾਂ",
    recentActivity: "ਹਾਲ ਦੀ ਗਤੀਵਿਧੀ",
    consultationCompleted: "ਸਲਾਹ ਮਸ਼ਵਰਾ ਪੂਰਾ ਹੋਇਆ",
    hoursAgo: "ਘੰਟੇ ਪਹਿਲਾਂ",
    nextAppointment: "ਅਗਲੀ ਮੁਲਾਕਾਤ",
    drSinghCheckup: "ਡਾ. ਸਿੰਘ ਦੀ ਜਾਂਚ ਨਿਰਧਾਰਿਤ",
    allDataSynced: "ਸਾਰਾ ਡੇਟਾ ਸਿੰਕ ਹੋ ਗਿਆ - ਔਫਲਾਈਨ ਲਈ ਤਿਆਰ",
    demoReady: "ਡੈਮੋ ਤਿਆਰ",
    
    pharmacyWallet: "ਫਾਰਮੇਸੀ ਵਾਲੇਟ",
    walletBalance: "ਵਾਲੇਟ ਬੈਲੇਂਸ",
    balanceLow: "ਬੈਲੇਂਸ ਘੱਟ ਹੈ",
    addMoney: "ਪੈਸੇ ਜੋੜੋ",
    addFunds: "ਪੈਸੇ ਜੋੜੋ",
    enterAmount: "ਰਾਸ਼ੀ ਦਰਜ ਕਰੋ",
    enterValidAmount: "ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ ਰਾਸ਼ੀ ਦਰਜ ਕਰੋ",
    amountAdded: "ਸਫਲਤਾਪੂਰਵਕ ਜੋੜਿਆ ਗਿਆ",
    insufficientBalance: "ਨਾਕਾਫੀ ਬੈਲੇਂਸ",
    outOfStock: "ਸਟਾਕ ਵਿੱਚ ਨਹੀਂ",
    purchaseSuccessful: "ਖਰੀਦ ਸਫਲ",
    downloadStatement: "ਸਟੇਟਮੈਂਟ ਸਫਲਤਾਪੂਰਵਕ ਡਾਊਨਲੋਡ ਕੀਤਾ ਗਿਆ",
    purchase: "ਖਰੀਦ",
    purchaseHistory: "ਖਰੀਦ ਦਾ ਇਤਿਹਾਸ",
    monthlyStatement: "ਮਹੀਨਾਵਾਰ ਸਟੇਟਮੈਂਟ",
    medicines: "ਉਪਲਬਧ ਦਵਾਈਆਂ",
    dosage: "ਖੁਰਾਕ",
    manufacturer: "ਨਿਰਮਾਤਾ",
    expiryDate: "ਮਿਆਦ ਦੀ ਤਾਰੀਖ",
    inStock: "ਸਟਾਕ ਵਿੱਚ",
    buy: "ਖਰੀਦੋ",
    availableBalance: "ਉਪਲਬਧ ਬੈਲੇਂਸ",
    thisMonth: "ਇਸ ਮਹੀਨੇ",
    totalExpenses: "ਕੁੱਲ ਖਰਚ",
    recentPurchases: "ਹਾਲ ਦੀ ਖਰੀਦਾਰੀ",
    noTransactions: "ਕੋਈ ਹਾਲ ਦੀ ਖਰੀਦਾਰੀ ਨਹੀਂ",
    quantity: "ਮਾਤਰਾ",
    price: "ਕੀਮਤ",
    transactionId: "ਟ੍ਰਾਂਜੈਕਸ਼ਨ ਆਈਡੀ",
    medicineDetails: "ਦਵਾਈ ਦਾ ਵੇਰਵਾ",
    totalAmount: "ਕੁੱਲ ਰਾਸ਼ੀ",
    buyNow: "ਹੁਣ ਖਰੀਦੋ",
    thisYear: "ਇਸ ਸਾਲ",
    
    subscriptionPlans: "ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਪਲਾਨ",
    currentPlan: "ਮੌਜੂਦਾ ਪਲਾਨ",
    planExpiry: "ਪਲਾਨ ਦੀ ਮਿਆਦ",
    renewPlan: "ਪਲਾਨ ਨਵੀਨੀਕਰਣ",
    upgradePlan: "ਪਲਾਨ ਅਪਗ੍ਰੇਡ",
    basicPlan: "ਬੇਸਿਕ ਪਲਾਨ",
    premiumPlan: "ਪ੍ਰੀਮੀਅਮ ਪਲਾਨ",
    familyPlan: "ਫੈਮਲੀ ਪਲਾਨ",
    monthlyBilling: "ਮਹੀਨਾਵਾਰ ਬਿਲਿੰਗ",
    yearlyBilling: "ਸਾਲਾਨਾ ਬਿਲਿੰਗ",
    savePercent: "20% ਬਚਾਓ",
    planFeatures: "ਪਲਾਨ ਦੀਆਂ ਸੁਵਿਧਾਵਾਂ",
    videoConsultations: "ਵੀਡੀਓ ਸਲਾਹ",
    aiDiagnostics: "ਏਆਈ ਨਿਦਾਨ",
    healthRecords: "ਸਿਹਤ ਰਿਕਾਰਡ",
    emergencySupport: "ਐਮਰਜੈਂਸੀ ਸਹਾਇਤਾ",
    familyMembers: "ਪਰਿਵਾਰ ਦੇ ਮੈਂਬਰ",
    prioritySupport: "ਪਰਾਥਮਿਕਤਾ ਸਹਾਇਤਾ",
    paymentHistory: "ਭੁਗਤਾਨ ਦਾ ਇਤਿਹਾਸ",
    nextBilling: "ਅਗਲੀ ਬਿਲਿੰਗ",
    manageSubscription: "ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਪ੍ਰਬੰਧਨ",
    cancelSubscription: "ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਰੱਦ ਕਰੋ",
    paymentMethod: "ਭੁਗਤਾਨ ਵਿਧੀ",
    cardNumber: "ਕਾਰਡ ਨੰਬਰ",
    expiryMonth: "ਮਿਆਦ ਦਾ ਮਹੀਨਾ",
    expiryYear: "ਮਿਆਦ ਦਾ ਸਾਲ",
    cvv: "ਸੀਵੀਵੀ",
    cardholderName: "ਕਾਰਡਹੋਲਡਰ ਦਾ ਨਾਮ",
    billingAddress: "ਬਿਲਿੰਗ ਪਤਾ",
    payNow: "ਹੁਣ ਭੁਗਤਾਨ ਕਰੋ",
    processingPayment: "ਭੁਗਤਾਨ ਪ੍ਰੋਸੈਸਿੰਗ...",
    paymentSuccessful: "ਭੁਗਤਾਨ ਸਫਲ",
    paymentFailed: "ਭੁਗਤਾਨ ਅਸਫਲ",
    subscriptionActive: "ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਸਰਗਰਮ",
    subscriptionExpired: "ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਮਿਆਦ ਖਤਮ",
    freeTrialActive: "ਮੁਫਤ ਟ੍ਰਾਇਲ ਸਰਗਰਮ",
    daysRemaining: "ਦਿਨ ਬਾਕੀ",
    unlimited: "ਅਸੀਮਿਤ",
    limited: "ਸੀਮਿਤ",
    notIncluded: "ਸ਼ਾਮਲ ਨਹੀਂ"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const translation = translations[language][key] || translations.en[key] || key;
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
